# Generated by Django 4.2.4 on 2023-08-03 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateField(default=datetime.datetime(2023, 8, 3, 7, 40, 58, 205083, tzinfo=datetime.timezone.utc))),
                ('updated', models.DateTimeField(default=datetime.datetime(2023, 8, 3, 7, 40, 58, 205083, tzinfo=datetime.timezone.utc))),
                ('status', models.CharField(choices=[('in', 'InProgress'), ('bl', 'Blocked'), ('co', 'Completed'), ('ca', 'Cancelled')], max_length=2)),
            ],
        ),
    ]
